// packages/ui/AddNetwork.vue
<!-- 
Scripts 
========================================================
-->
<script setup>
    import { ref } from 'vue';

    var wallet = ref(false);
    if (typeof window?.ethereum !== 'undefined') {
      wallet = ref(true)
    }

    const props = defineProps({
      testnet: Boolean,
      chainName: String,
      chainId: Number,
      nativeCurrencyName: String,
      nativeCurrencySymbol: String,
      nativeCurrencyDecimals: {
        type: Number,
        default: 18
      },
      rpcUrl: String,
      blockExplorerUrl: String
    });

    /**
     * Main function that adds wallet configuration
     */
    const addNetwork = () => {
      if (!wallet) {
        return;
      }
      window?.ethereum.request({
        method: 'wallet_addEthereumChain',
        params: [
          {
            chainId: "0x" + (props?.chainId ?? 0).toString(16),
            chainName: props?.chainName,
            nativeCurrency: {
              name: props.nativeCurrencyName,
              symbol: props.nativeCurrencySymbol,
              decimals: props?.nativeCurrencyDecimals
            },
            rpcUrls: [props.rpcUrl],
            blockExplorerUrls: [props.blockExplorerUrl]
          }
        ]
      })
    }
</script>

<!-- 
Template 
========================================================
-->
<template>
  <button
    class="type-primaryw-iconresting-type-primaryw-iconresting" 
    v-if="wallet" v-on:click="addNetwork">
    <span v-if="props.testnet">Add Testnet</span>
    <span v-else>Add Berachain</span>
  </button>
  <button
    class="type-primaryw-iconresting-type-primaryw-iconresting" 
    disabled
    v-else>
    Wallet Not Supported
  </button>
</template>

<!-- 
Styles 
========================================================
-->
<style>
  .type-primaryw-iconresting-type-primaryw-iconresting {
    font-weight: 600;
    text-align: left;
    color: rgb(44, 26, 22);
    border-radius: 8px;
    height: 44px;
    width: auto;
    align-items: center;
    justify-content: center;
    display: inline-flex;
    gap: 4px;
    box-shadow: 0px 0px 0px 1px #dbb180f5 inset;
    background: var(--vp-c-brand-2);
    padding-right: 16px;
    padding-left: 16px;
    padding-bottom: 8px;
    padding-top: 8px;
    box-sizing: border-box;
    font-size: 18px;
    line-height: 28px;
  }

  .type-primaryw-iconresting-type-primaryw-iconresting[disabled] {
    opacity: 0.3;
    cursor: not-allowed;
  }

  .type-primaryw-iconresting-type-primaryw-iconresting[disabled]:hover {
    background: var(--vp-c-brand-3);
  }

  .type-primaryw-iconresting-type-primaryw-iconresting:hover {
    background-image: -webkit-linear-gradient(117deg,#FF8A00F5 25%,#FFC738);
  }
</style>

// snippets/AddNetwork.jsx
const LOG_PREFIX = "[AddNetwork]";

export const AddNetwork = (props) => {
  const {
    chainId = 80094,
    chainName = "Berachain",
    nativeCurrencyName = "BERA Token",
    nativeCurrencySymbol = "BERA",
    nativeCurrencyDecimals = 18,
    rpcUrl = "https://rpc.berachain.com/",
    blockExplorerUrl = "https://berascan.com/",
    isTestnet = false,
  } = props || {};

  const [hasWallet, setHasWallet] = useState(false);

  useEffect(() => {
    const hasEthereum = typeof window !== "undefined" && typeof window.ethereum !== "undefined";
    setHasWallet(!!hasEthereum);
    if (typeof console !== "undefined" && console.log) {
      console.log(LOG_PREFIX + " wallet detected:", !!hasEthereum);
    }
  }, []);

  const addNetwork = () => {
    if (!hasWallet || typeof window === "undefined" || !window.ethereum) {
      if (typeof console !== "undefined" && console.warn) {
        console.warn(LOG_PREFIX + " addNetwork called but no wallet available");
      }
      return;
    }
    const hexChainId = "0x" + Number(chainId).toString(16);
    const params = {
      chainId: hexChainId,
      chainName: String(chainName),
      nativeCurrency: {
        name: String(nativeCurrencyName),
        symbol: String(nativeCurrencySymbol),
        decimals: Number(nativeCurrencyDecimals),
      },
      rpcUrls: [String(rpcUrl)],
      blockExplorerUrls: [String(blockExplorerUrl)],
    };
    if (typeof console !== "undefined" && console.log) {
      console.log(LOG_PREFIX + " addNetwork click", { chainName, isTestnet, chainId: hexChainId, rpcUrl, blockExplorerUrl, fullParams: params });
    }
    window.ethereum
      .request({ method: "wallet_addEthereumChain", params: [params] })
      .then(function (result) {
        if (typeof console !== "undefined" && console.log) {
          console.log(LOG_PREFIX + " wallet_addEthereumChain result:", result);
        }
      })
      .catch(function (err) {
        if (typeof console !== "undefined" && console.error) {
          console.error(LOG_PREFIX + " wallet_addEthereumChain error:", err);
        }
      });
  };

  const baseStyle = {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "140px",
    height: "44px",
    padding: "0 16px",
    borderRadius: "8px",
    borderWidth: "2px",
    fontWeight: 600,
    cursor: "pointer",
  };

  if (!hasWallet) {
    return (
      <button
        type="button"
        disabled
        style={{
          ...baseStyle,
          backgroundColor: "#4b5563",
          color: "#d1d5db",
          borderColor: "#6b7280",
          cursor: "not-allowed",
          opacity: 0.8,
        }}
      >
        Wallet not detected
      </button>
    );
  }

  return (
    <button
      type="button"
      onClick={addNetwork}
      style={{
        ...baseStyle,
        backgroundColor: "#E17726",
        color: "#1a1a1a",
        borderColor: "#c96516",
        boxShadow: "0 1px 3px rgba(0,0,0,0.25)",
      }}
    >
      Add {chainName}
    </button>
  );
};
